kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployments
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sowmi
  template:
    metadata:
      labels:
        name: sowmi
    spec:
      containers:
        - name: c1
          image: httpd
          ports:
            - containerPort: 80
