kind: Pod
apiVersion: v1
metadata:
  name: nodelabel
spec:
  containers:
    - name: c1
      image: ubuntu
      command: ["/bin/bash", "-c","while true; do echo Hello-sai; sleep 5; done"]
  nodeSelector:
      mynode: arjun
