kind: ReplicationController
apiVersion: v1
metadata:
  name: replicapod
spec:
  replicas: 2
  selector:
    myname: sai
  template:
    metadata:
      labels:
        myname: sai
    spec:
      containers:
          - name: c1
            image: ubuntu
            command: ["/bin/bash", "-c","while true; do echo Hell-sa i; sleep 5; done"]

