kind: ReplicaSet 
apiVersion: apps/v1
metadata:
  name: replicapod
spec:
  replicas: 2
  selector:
    matchExpressions: 
      - key: myname
        operator: In
        values:
          - sai
          - saii
  template:
    metadata:
      labels:
        myname: sai
    spec:
      containers:
          - name: c1
            image: ubuntu
            command: ["/bin/bash", "-c","while true; do echo Hell-sai; sleep 5; done"]


